[workflow]
name = 'AIP'

# optionally allow for running a different HTML script
presentation = 'cpg'

# where to register outputs, if at all
status_reporter = 'metamist'

## override clinvar results
#clinvar_decisions = "HailTable path to private ClinVar"
#clinvar_pm5 = "HailTable path to ClinVar PM5"

obo_file = 'gs://cpg-common-test/references/aip/hpo_terms.obo'

[images]
aip = "australia-southeast1-docker.pkg.dev/cpg-common/images/cpg_aip:latest"

[panels]
default_panel = 137
panelapp = 'https://panelapp.agha.umccr.org/api/v1/panels'
panel_month_delta = 12
require_pheno_match = ['FLG', 'GJB2', 'F2', 'F5']

[clinvar]
filter_benign = ['illumina laboratory services; illumina']

[moi_tests]
# thresholds for different filters during the MOI checks
gnomad_dominant = 0.001
gnomad_max_homs_dominant = 0
gnomad_max_homs_recessive = 1
gnomad_max_ac_dominant = 10
gnomad_max_hemi = 1

[csq]
# variables affecting how the VCF variants are parsed, and AnalysisVariant objects are populated
csq_string = ['allele', 'consequence', 'symbol', 'gene', 'feature', 'mane_select', 'biotype', 'exon', 'hgvsc', 'hgvsp', 'cdna_position', 'cds_position', 'amino_acids', 'protein_position', 'variant_class', 'ensp', 'lof', 'sift', 'polyphen', 'am_class', 'am_pathogenicity']

[filter]
# variables for the hail operations, including CSQ sets and filter thresholds
ac_threshold = 0.01
additional_csq = ['missense_variant']
af_semi_rare = 0.01
cadd = 28.1
critical_csq = ['frameshift_variant', 'splice_acceptor_variant', 'splice_donor_variant', 'start_lost', 'stop_gained', 'stop_lost', 'transcript_ablation']
gerp = 1.0
eigen = 0.25
max_parent_ab = 0.05
minimum_depth = 10
polyphen = 0.99
revel = 0.77
sift = 0.0
spliceai = 0.5

[categories]
1 = 'ClinVar Pathogenic'
2 = 'New Gene-Disease Association'
3 = 'High Impact Variant'
4 = 'de Novo'
5 = 'High SpliceAI Score'
6 = 'AlphaMissense P/LP'
pm5 = 'ACMG PM5 - missense in same residue as known pathogenic'
support = 'High in Silico Scores'

[hail]
cancel_after_n_failures = 1
default_timeout = 6000
default_memory = 'highmem'

[references]
genome_build = 'GRCh38'

# per-cohort section
#clinvar_filter = when running a clinvar re-summary, remove submissions by these sites. Default = no removal
#cohort_panels = any panel IDs to be applied to this cohort, even if not otherwise phenotype-matched
#gene_prior = if a specific gene list is to be used to determine Cat 2 (new gene-disease associations), provide the filepath here

# this content is not stored in this repository due to data protection concerns.
# Instead, AIP runs in production-pipelines should use the config from github::production-pipelines-configuration